### PR TITLE
Add the k4RecTracker package

### PR DESCRIPTION
**Pull request by BrieucF**
BEGINRELEASENOTES
- Add the k4RecTracker package, hosting edm4hep based Gaudi algorithms for tracking detectors (and similar) digitization and reconstruction

ENDRELEASENOTES

### CODE REVIEW

**Review by jmcarcell — APPROVED** [review]

**Comment by jmcarcell** [comment]
Will we have reconstruction algorithms there too? Then the name of the repo is maybe not the best fit for any reconstruction algorithm. We also have k4Reco and should think where to distribute algorithms in the future

**Comment by BrieucF** [comment]
> Will we have reconstruction algorithms there too? Then the name of the repo is maybe not the best fit for any reconstruction algorithm. We also have k4Reco and should think where to distribute algorithms in the future

Yes, I would plan to have tracking algorithms there. I think it still makes sense to separate local reconstruction algorithms between tracking, calorimeter clustering, etc, because people will in general work only in one of these sub-fields and may not like to compile the whole reconstruction each time. But I am of course open to other solutions if people have different opinions.

**Comment by BrieucF** [comment]
Will there be a nightly build tomorrow for me to check that everything works as expected?

**Comment by jmcarcell** [comment]
If everything builds yes, otherwise no

**Comment by BrieucF** [comment]
Ok, how can I "subscribe" to be notified daily whether the nightly build was successful or not, and why?

**Pull request merged**
