### PR TITLE
Format the whole repository using black and add a pre-commit config

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Format all packages and python scripts using black to be consistent with upstream spack formatting.
- Add a pre-commit configuration and github action
ENDRELEASENOTES

### CODE REVIEW

**Comment by jmcarcell** [comment]
To avoid this commit in `git blame` it will be added in `.git-blame-ignore-revs` so that `git blame --ignore-revs-file /path/to/key4hep-spack/.git-blame-ignore-revs package.py` works fine

**Comment by tmadlener** [comment]
Oh, that is a nice feature. I wasn't aware of that.

**Comment by andresailer** [comment]
Also in github: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by tmadlener** [comment]
:exploding_head:

**Pull request merged**
