### PR TITLE
Making release versions list unique and reversing order they appear in

### PR DESCRIPTION
**Pull request by kjvbrt**
BEGINRELEASENOTES
- Making release versions list unique and reversing order they appear in

ENDRELEASENOTES

### CODE REVIEW

**Comment by jmcarcell** [comment]
Why `uniq`, is there any case where they are not unique? I think they should be. I prefer not reversing because then interactively you get the most recent ones at the end, which is typically where I would say it's more likely someone is searching, and scrolling up isn't necessary.

**Comment by kjvbrt** [comment]
Currently I get this output:
```
Release almalinux9 not found, this is a list of the available releases:
2024-03-07
2024-03-07
2024-03-07
2024-03-08
2024-03-08
2024-03-08
2024-03-08
2024-03-12
2024-03-12
2024-03-12
2024-03-12
2024-03-13
2024-03-13
2024-03-13
2024-03-13
2024-03-14
2024-03-14
2024-03-14
2024-03-14
2024-03-15
2024-03-15
2024-03-15
2024-03-15
2024-03-16
2024-03-16
2024-03-16
2024-03-16
2024-03-17
2024-03-17
2024-03-17
2024-03-17
2024-03-20
2024-03-20
2024-03-20
2024-03-20
2024-03-21
2024-03-21
2024-03-21
2024-03-21
2024-03-22
2024-03-22
2024-03-22
2024-03-22
2024-03-23
2024-03-23
2024-03-23
2024-03-23
2024-03-24
2024-03-24
2024-03-24
2024-03-24
2024-03-25
2024-03-25
2024-03-25
2024-03-25
2024-03-26
2024-03-26
2024-03-26
2024-03-26
2024-03-28
2024-03-28
2024-03-28
2024-03-28
2024-03-29
2024-03-29
2024-03-29
2024-03-29
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-31
2024-03-31
2024-03-31
2024-03-31
2024-04-01
2024-04-01
2024-04-01
2024-04-01
2024-04-02
2024-04-02
2024-04-02
2024-04-02
2024-04-03
2024-04-03
2024-04-03
2024-04-04
2024-04-04
2024-04-04
2024-04-04
2024-04-05
2024-04-05
2024-04-05
2024-04-06
2024-04-06
2024-04-06
2024-04-06
2024-04-07
2024-04-07
2024-04-07
2024-04-07
2024-04-08
2024-04-08
2024-04-08
2024-04-08
2024-04-09
2024-04-09
2024-04-09
2024-04-09
2024-04-10
2024-04-10
2024-04-10
2024-04-10
2024-04-11
2024-04-11
2024-04-11
2024-04-11
2024-04-15
2024-04-15
2024-04-15
2024-04-15
2024-04-16
2024-04-16
2024-04-16
2024-04-16
2024-04-17
2024-04-17
2024-04-17
2024-04-17
2024-04-18
2024-04-18
2024-04-18
2024-04-18
2024-04-19
2024-04-19
2024-04-19
2024-04-19
2024-04-20
2024-04-20
2024-04-20
2024-04-21
2024-04-21
2024-04-21
2024-04-22
2024-04-22
2024-04-22
2024-04-24
2024-04-24
2024-04-25
2024-04-25
2024-04-25
2024-04-25
2024-04-26
2024-04-26
2024-04-26
2024-04-26
2024-04-27
2024-04-27
2024-04-27
2024-04-28
2024-04-28
2024-04-28
2024-04-29
2024-04-29
2024-04-29
2024-05-02
2024-05-02
2024-05-02
2024-05-02
2024-05-03
2024-05-03
2024-05-03
2024-05-03
2024-05-04
2024-05-04
2024-05-04
2024-05-04
2024-05-05
2024-05-05
2024-05-05
2024-05-05
2024-05-06
2024-05-06
2024-05-06
2024-05-06
2024-05-09
2024-05-09
2024-05-09
2024-05-16
2024-05-16
2024-05-16
2024-05-17
2024-05-17
2024-05-17
2024-05-18
2024-05-18
2024-05-18
2024-05-19
2024-05-19
2024-05-19
2024-05-20
2024-05-20
2024-05-20
2024-05-21
2024-05-21
2024-05-21
2024-05-22
2024-05-22
2024-05-22
2024-05-23
2024-05-23
2024-05-23
2024-05-24
2024-05-24
2024-05-24
2024-05-25
2024-05-25
2024-05-25
2024-05-26
2024-05-26
2024-05-26
2024-05-27
2024-05-27
2024-05-27
2024-05-28
2024-05-28
2024-05-28
2024-05-29
2024-05-29
2024-05-29
2024-05-30
2024-05-30
2024-05-30
2024-05-31
2024-05-31
2024-05-31
2024-06-01
2024-06-01
2024-06-01
2024-06-02
2024-06-02
2024-06-02
2024-06-03
2024-06-03
2024-06-03
2024-06-04
2024-06-04
2024-06-04
2024-06-05
2024-06-05
2024-06-05
2024-06-06
2024-06-06
2024-06-06
2024-06-07
2024-06-07
2024-06-07
2024-06-08
2024-06-08
2024-06-08
2024-06-09
2024-06-09
2024-06-09
2024-06-10
2024-06-10
2024-06-10
2024-06-11
2024-06-11
2024-06-11
2024-06-12
2024-06-12
2024-06-12
2024-06-13
2024-06-13
2024-06-13
2024-06-14
2024-06-14
2024-06-14
2024-06-15
2024-06-15
2024-06-15
2024-06-16
2024-06-16
2024-06-16
2024-06-17
2024-06-17
2024-06-17
2024-06-18
2024-06-18
2024-06-18
2024-06-19
2024-06-19
2024-06-19
2024-06-20
2024-06-20
2024-06-20
2024-06-26
2024-06-26
2024-06-26
2024-06-27
2024-06-27
2024-06-27
2024-06-28
2024-06-28
2024-06-28
2024-06-29
2024-06-29
2024-06-29
2024-06-30
2024-06-30
2024-06-30
2024-07-01
2024-07-01
2024-07-01
2024-07-02
2024-07-02
2024-07-02
2024-07-03
2024-07-03
2024-07-03
2024-07-04
2024-07-04
2024-07-04
2024-07-05
2024-07-05
2024-07-06
2024-07-06
2024-07-06
2024-07-07
2024-07-07
2024-07-07
2024-07-08
2024-07-08
2024-07-08
2024-07-09
2024-07-09
2024-07-09
2024-07-10
2024-07-10
2024-07-10
2024-07-11
2024-07-11
2024-07-11
2024-07-12
2024-07-12
2024-07-12
2024-07-13
2024-07-13
2024-07-13
2024-07-14
2024-07-14
2024-07-14
2024-07-15
2024-07-15
2024-07-15
2024-07-16
2024-07-16
2024-07-16
2024-07-17
2024-07-17
2024-07-17
2024-07-18
2024-07-18
2024-07-18
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
releases
Aborting...
```

**Comment by jmcarcell** [comment]
Can you try again with the current version of the script? I don't see it happening for me
``` bash
$ source setup.sh --list-releases almalinux9
2024-05-09
2024-05-16
2024-05-17
2024-05-18
2024-05-19
2024-05-20
2024-05-21
2024-05-22
2024-05-23
2024-05-24
2024-05-25
2024-05-26
2024-05-27
2024-05-28
2024-05-29
2024-05-30
2024-05-31
2024-06-01
2024-06-02
2024-06-03
2024-06-04
2024-06-05
2024-06-06
2024-06-07
2024-06-08
2024-06-09
2024-06-10
2024-06-11
2024-06-12
2024-06-13
2024-06-14
2024-06-15
2024-06-16
2024-06-17
2024-06-18
2024-06-19
2024-06-20
2024-06-26
2024-06-27
2024-06-28
2024-06-29
2024-06-30
2024-07-01
2024-07-02
2024-07-03
2024-07-04
2024-07-06
2024-07-07
2024-07-08
2024-07-09
2024-07-10
2024-07-11
2024-07-12
2024-07-13
2024-07-14
2024-07-15
2024-07-16
2024-07-17
2024-07-18
2024-07-19
2024-07-20
2024-07-21
2024-07-22
2024-07-23
2024-07-24
2024-07-25
2024-07-26
2024-07-27
2024-07-28
2024-07-29
2024-07-30
2024-07-31
2024-08-01
2024-08-03
2024-08-04
2024-08-05
```

**Comment by jmcarcell** [comment]
Closing as this should be fixed, feel free to reopen if not.

**Pull request closed without merging**
