### PR TITLE
dd4hep: enable hepmc3 support

### PR DESCRIPTION
**Pull request by andresailer**
DD4hep: Enable the HepMC3 input reader for ddsim.

### CODE REVIEW

**Review by vvolkl — APPROVED** [review]
Thanks! Now that Root v6.22/06 is released, I had planned to make a new build against that (updating spack at the same time, possibly already using the new concretizer), or do you want a build with dd4hep+hepmc3 against the current root?

**Comment by andresailer** [comment]
We need to merge a few more bug fixes to dd4hep before a release makes sense. 
Also the EDM4hep output moving to DD4hep, we need to move edm4hep spack to upstream spack for that, right? (To add the variant to the DD4hep recipe)

**Comment by vvolkl** [comment]
Ok. Yes, for edm4hep that's true. I'll move it upstream once we have a new tag (so I can drop the delphes / dd4hep dependencies from the recipe)

**Comment by vvolkl** [comment]
@andresailer I think I have to revert this, otherwise users and the ci using spack according to our instructions will build dd4hep from scratch instead of using the existing installation. I'd propose to make a `develop` branch with changes that affect the concretization in this way.

**Comment by andresailer** [comment]
Thanks for taking care of this! Sorry for the inconvenience!

**Pull request merged**
