### PR TITLE
Add utility to automatically generate g4data externals config

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Add a spack extension command `g4data` that automatically collects the geant4-data packages that are installed and dumps them into a `package.yaml` compatible format marking all of them as non-buildable.

ENDRELEASENOTES

This is a spack [extension](https://spack.readthedocs.io/en/latest/extensions.html), so it is necessary to add it to `config.yaml` via
```yaml
config:
  extensions:
    - <path-to>/key4hep-spack/spack-utilities
```
With that in place it is possible to just do
```sh
spack g4data
```
to collect all installed geant4-data packages and mark them as non-buildable. Obviously, you will have to put the output to a suitable `packages.yaml` (or similar) file in order to make spack aware of this.

### CODE REVIEW

**Comment by vvolkl** [comment]
Why a spack extension instead of adding support for `spack external find g4data`?

**Comment by tmadlener** [comment]
I had another look and it seems that we could use `geant4-config` to locate the installed datasets and with some string manipulation also their versions. However, that would mean that we need a geant4 installation to do it. 

With all that in mind, I would like to keep this small utility, even if there is `external find` support for the geant4 data packages, because this allows me to produce a yaml file that I can include into an environment, whereas with `external find` I can only populate the different configuration scopes of spack, but as far as I can tell not into an environment only configuration.

**Comment by wdconinc** [comment]
You can add externals to an environment, and`spack external find` when called from inside an environment will by default only add those externals to the environment itself.

**Comment by wdconinc** [comment]
FYI upstream at https://github.com/spack/spack/pull/29591

**Comment by tmadlener** [comment]
After having played a bit with that myself, I still think this is the simpler solution for this problem ;) There is quite a bit of code involved in that, and it will require parsing the version information from paths, instead of being able to rely on the spack installation database.

However, having `external find` support is probably still something worth having.

**Comment by tmadlener** [comment]
I think this is no longer necessary as the new conretizer is much better at picking up existing data packages.

**Pull request closed without merging**
