### PR TITLE
Update container that is used in CI

### PR DESCRIPTION
**Pull request by tmadlener**
Dockerhub hosted one has been removed due to potential clash with new docker TOS

Image from https://github.com/AIDASoft/management/pkgs/container/centos7

### CODE REVIEW

**Comment by tmadlener** [comment]
I have no idea why github seems to be trying to run the outdated workflow file for the `concretize-lxplus-comment-bot` workflow. Clicking on the "View workflow file" shows the one from this PR, but it looks like the one from master is currently being run. Everything seems to work for the `concretize-lxplus` workflow

**Comment by andresailer** [comment]
It is using https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
https://github.com/key4hep/key4hep-spack/blob/f5f1b98e5f4df53581c4f88331d8f09466d4808f/.github/workflows/concretize-lxplus-pr-target.yaml#L2

**Comment by vvolkl** [comment]
Yes, it's because  this workflow needs a github secret to post its comment, github doesn't let it run on the usual `pull_request` trigger, instead, it is `pull_request target` - which is the same except that it runs on the current master instead of the PR branch (I do actually set up the PR branch in the workflow to make this work)

Should be fine once this is merged.

**Comment by tmadlener** [comment]
:+1: Thanks for pointing that out

**Pull request merged**
