### PR TITLE
[ilcsoft] add  bundle package

### PR DESCRIPTION
**Pull request by vvolkl**

### CODE REVIEW

**Review by tmadlener — COMMENTED** [review]
Hi Valentin, I think this looks good, but I am not entirely sure what the intention is. Depending on that I might have some additional comments.

Should this mainly serve as a somewhat logical separation of packages in the key4hep stack? I.e. make the key4hep bundle package a bit easier to manage by splitting it into smaller bundle packages that contain mainly software from the ilcsoft universe (in this case) and other parts, e.g. fccsw?

Or, is the final goal to have this as a replacement/successor of iLCInstall? I have at some point started to look into this possibility with spack, but apart from some preliminary tests, and at least a basic setup seems to be possible. However, I haven't really checked in detail where things start to break.

**Comment by andresailer** [comment]
Hi Thomas, the idea was (in view of LCWS) say that is would be possible to install ilcsoft via spack.

**Comment by tmadlener** [comment]
Ah, I see. That should definitely be possible. I have checked with the key4hep-stack and the [ILD tutorial](https://github.com/ILDAnaSoft/ILDDoc/blob/master/tutorial/gaede_ilcsoft_tutorial.pdf) in the past and that works basically by copy-pasting if you set 2 env variables (`export DD4HEP=$DD4hepINSTALL/examples` and you have to replace `lcgeo_DIR` with `LCGEO` when using the key4hep installation).

If we want a full install, I am wondering whether all the things in the base of iLCInstall are also present. E.g. root, geant4 and dd4hep are not explicitly mentioned here, but are potentially pulled in through dependencies. However, I am not sure if, e.g. `ddsim` becomes available on `PATH` that way.

**Comment by vvolkl** [comment]
Yes, as Andre mentioned, this is mostly to make it more clear to newcomers to key4hep that ilcsoft is completely part of the key4hep-stack. But since ilcsoft gets a version number when you install it with ilcinstall, it makes sense to  have a package in spack you can give this version number too. This then also helps to install a "pinned" release version, via an environment. In my opinion, it is still good practice to install the whole key4hep-stack by default, even if you don't need some experiment packages. and at one point we'll have more common packages so the distinction ilcsoft / key4hep will be a bit more blurry.

@tmadlener Could you maybe check again the environment variables? For lcgeo both should be there https://github.com/key4hep/key4hep-spack/blob/release/packages/lcgeo/package.py#L55 and for dd4hep that would be easy to add. I think we agreed that we would prefer using `PACKAGENAME=<package-prefix>/share/PackageName` by default, but keep already used env vars for backwards compatibility.

**Comment by tmadlener** [comment]
> @tmadlener` Could you maybe check again the environment variables?

Just checked with the `2020-03-09-b` release and there the following things are missing / not as expected (from the point of view of the ILD tutorial).
- `lcgeo_DIR` should point to the same place as `LCGEO` does at the moment for the ILD tutorial to work. Also I think `LCGEO` is not following our agreed on schema, because it points to `<package-prefix>/share/lcgeo/compact` but should instead point to `<package-prefix>/share/lcgeo`, right? 
- `DD4HEP` is not set at the moment. Here, the export to `$DD4hepINSTALL/examples` is necessary, because it is read in a python script. Since dd4hep does not have a `share` install directory, here we could maybe deviate from our usual scheme and let `DD4HEP` point to `<package-prefix>/examples` instead.

**Comment by vvolkl** [comment]
True, actually the spack install should maybe install to `<prefix>/share/lcgeo` instead of `<prefix>/share/lcgeo/compact`, since the compact still follows in the subdirectories. See https://github.com/key4hep/key4hep-spack/compare/release...vvolkl:env?expand=1

For lcgeo_DIR, I have no objections, but I was under the impressions that other part of ilcsoft use it in the way it is here.

For DD4HEP, there is not only `examples`, but also `DDDetectors` in the top level directory that could be accessed with this env var, but if it is already used like this, ok.

**Comment by vvolkl** [comment]
> If we want a full install, I am wondering whether all the things in the base of iLCInstall are also present. E.g. root, geant4 and dd4hep are not explicitly mentioned here, but are potentially pulled in through dependencies. However, I am not sure if, e.g. `ddsim` becomes available on `PATH` that way.

@tmadlener, Any dependencies of the ilcsoftpackages will also be installed and set up, which definitely includes root, geant4 and dd4hep.

**Pull request merged**
