### PR TITLE
Added new versions of pandorapfa package

### PR DESCRIPTION
**Pull request by bartosik-hep**
BEGINRELEASENOTES
- Added new versions `3.25.1 - 4.3.1` for the `pandorapfa` package

ENDRELEASENOTES

### CODE REVIEW

**Comment by bartosik-hep** [comment]
I didn't touch the preferred version, which is still `3.24.0`.
There are no release notes for [any of these tags](https://github.com/PandoraPFA/PandoraPFA/tags). Should I update preferred version to `4.3.1`?

**Comment by andresailer** [comment]
`LCContent` which is what matters for us hasn't seen any recent update.
Anything mandatory in the new versions? Support for new compilers, OS etc.?

**Comment by bartosik-hep** [comment]
There was only a change of `eigen` version in [`v03-25-03`](https://github.com/PandoraPFA/PandoraPFA/commit/2743a083b0f986b66cb75e794e61674554f720c7). 
Everything else stayed the same through all the new versions, including the `PandoraSDK ` version.

**Comment by jmcarcell** [comment]
> I didn't touch the preferred version, which is still `3.24.0`. There are no release notes for [any of these tags](https://github.com/PandoraPFA/PandoraPFA/tags). Should I update preferred version to `4.3.1`?

What do you mean @bartosik-hep? The preferred version will now be 4.3.1 since it's the last one and `preferred=True` is not specified in any of the versions

**Pull request merged**
